stages:

  FETCHING_DATA:
    cmd: python src/stage_01_retrieve_html.py --config config/config.yaml
    deps:
      - src/stage_01_retrieve_html.py
      - src/utils/all_utils.py
      - config/config.yaml
      
    outs:
      - artifacts/Data_archive/dementia_dataset/dementia_dataset.csv
      - logs/stage_01_running_logs.log

  #Extracting and combining data:
  # cmd: python src/stage_02_EDA.py --config config/config.yaml
  #  deps:
  #    - src/stage_02_Extract_combine.py
  #    - src/stage_01_retrieve_html.py
  #    - src/utils/all_utils.py
  #    - config/config.yaml
  #    #- artifacts/data/AQI/aqi2013.csv
  #    - artifacts/Data_archive/AQI/
  #    - artifacts/Data_archive/Html_Data
  #    - requirements.txt      
  #  outs:
  #    - artifacts/Data_archive/Real-Data/Real_Combine.csv


  Exploratory_Data_Analysis:
    cmd: python src/stage_02_EDA.py --config config/config.yaml
    deps:
      - src/stage_02_EDA.py
      - artifacts/Data_archive/dementia_dataset/dementia_dataset.csv
      - src/utils/all_utils.py
      - config/config.yaml
      - requirements.txt
    outs:
      - artifacts/reports_dir/graphs_dir/
      - artifacts/Data_archive/Real-Data/Cleaned_Real_Combined_data.csv
      - logs/stage_02_running_logs.log
    
  Splitting_Data:
    cmd: python src/stage_03_splitting_data.py --config config/config.yaml --params params.yaml
    deps:
      - src/stage_03_splitting_data.py
      - artifacts/Data_archive/Real-Data/Cleaned_Real_Combined_data.csv
      - src/utils/all_utils.py
      - config/config.yaml
      - requirements.txt
      - params.yaml
    outs:
      - artifacts/split_data_dir/
      - logs/stage_03_running_logs.log
 
  TRAINING_AND_GENERATING_MODEL:
    cmd:  python src/stage_04_xgboost_regression.py  --config config/config.yaml --params params.yaml
    deps:
      - src/stage_04_xgboost_regression.py
      - artifacts/split_data_dir/train_data_dir
      - src/utils/all_utils.py
      - config/config.yaml
      - requirements.txt
      - params.yaml
    outs:
      - artifacts/trained_model/
      - artifacts/reports_dir/scores.json
      - logs/stage_04_running_logs.log


  TESTING_AND_GENERATING_GRAPH:
    cmd:  python src/stage_05_model_accuracy_testing.py   --config config/config.yaml 
    deps:
      - src/stage_05_model_accuracy_testing.py
      - artifacts/split_data_dir/test_data_dir
      - artifacts/trained_model/
      - src/utils/all_utils.py
      - config/config.yaml
      - requirements.txt
    outs:
      - artifacts/reports_dir/trained_model_graph_dir
      - logs/stage_05_running_logs.log

# cannot use this stage for git hub action
#  LAUNCHING_WEB_APPLICATION:
#    cmd:  python app.py 
#    deps:
#      - app.py
#      - templates/
#      - artifacts/trained_model/
#      - static/
#     - config/config.yaml
    

  