# all the locations of different directories will be here
Data:
  local_source_download_path: .RAW__dementia_dataset
  site_name: https://storage.googleapis.com/kaggle-data-sets/1519608/2509179/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20220508%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220508T161634Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=02c5a97a010e931c39cc82f6ae71984e05e9ab0b387c70257995bc5b46ba74b280e19fbf3d9d11a4ceebff313e1188c0962d102d4fb4f9d8e33c642cc8e621c7f72c53049b2832f74671ebb2bc56745244f5e4f7ccaff731552f48345ff90af3eb2e1533a0c53b03b4d19468dc1a83daa6a99362c66efc959e41ce777040aa260311149ee52f88adb7e406d73ac3a8f40cb41fad683047db06d2f70a20d0d7aa9a4298a53f159db8e7cbedac9c42c0f8b9d40052f386063ab4eda64c9231c1cbb938a93171f7d6271ec5feadbd19590adc440cf18503c707f16aef73585140f7e1f37cfb33417fe5d4eae2b8133cb7b7712b216f0715256a91bf4a8d0c75a147
  #city_code: ws-421820.html
  

artifacts: 
  artifacts_dir: artifacts
  data_local_dir: Data_archive
  raw_data_dir: dementia_dataset
  #aqi_data_dir: AQI
  #html_data_dir: Html_Data
  real_data_dir: Real-Data
  real_data_combined_file: dementia_dataset.csv
  cleaned_real_data_file: Cleaned_Real_Combined_data.csv
   

  split_data: 
    split_data_dir: split_data_dir
    train_data_dir: train_data_dir
    test_data_dir: test_data_dir
    train_data_file: train_data.csv
    test_data_file: test_data.csv
  
  model: 
    model_dir: trained_model
    decision_tree_reg: decision_tree_regression.pk1
    lasso_reg: la sso_regression.pk1
    ridge_reg: ridge_regression.pk1
    linear_reg: linear_regression.pk1
    random_forest_reg: random_forest_regression.pk1
    xgboost_reg: xgboost_regression.pk1
    finalized_model: finalized_model_ml.sav
    logistic_reg_model: logistic_reg_model.sav
    Alzheimer_model_latest : Alzheimer_model_latest.h5
    logistic_reg_RFE_model : logistic_reg_RFE_model.pk1
  
  reports: 
    reports_dir: reports_dir
    scores: scores.json
    
    graphs:
      graphs_dir: graphs_dir
      trained_model_graph_dir: trained_model_graph_dir