# all the locations of different directories will be here
Data:
  local_source_download_path: ../dementia_dataset

  #city_code: ws-421820.html
  #alzheimers_mri_local_source: ../Alzheimer_s Dataset
  #alzheimers_mri_remote_source: https://drive.google.com/drive/folders/11on8iRLolH6uPQ4KDwn7a-WdguOtnNR8?usp=sharing

  alzheimers_mri_source_download_dirs:
    - ../Alzheimer_s Dataset/train/MildDemented
    - ../Alzheimer_s Dataset/train/ModerateDemented
    - ../Alzheimer_s Dataset/train/NonDemented
    - ../Alzheimer_s Dataset/train/VeryMildDemented

    - ../Alzheimer_s Dataset/test/MildDemented
    - ../Alzheimer_s Dataset/test/ModerateDemented
    - ../Alzheimer_s Dataset/test/NonDemented
    - ../Alzheimer_s Dataset/test/VeryMildDemented    

  alzheimers_mri_local_data_dirs:
    - artifacts/Data_archive/alzheimers_dataset/train/MildDemented
    - artifacts/Data_archive/alzheimers_dataset/train/ModerateDemented
    - artifacts/Data_archive/alzheimers_dataset/train/NonDemented
    - artifacts/Data_archive/alzheimers_dataset/train/VeryMildDemented

    - artifacts/Data_archive/alzheimers_dataset/test/MildDemented
    - artifacts/Data_archive/alzheimers_dataset/test/ModerateDemented
    - artifacts/Data_archive/alzheimers_dataset/test/NonDemented
    - artifacts/Data_archive/alzheimers_dataset/test/VeryMildDemented    


artifacts: 
  artifacts_dir: artifacts
  data_local_dir: Data_archive
  raw_data_dir: dementia_dataset
  alzheimers_mri_data_dir: alzheimers_dataset
  real_data_dir: Real-Data
  real_data_combined_file: dementia_dataset.csv
  cleaned_real_data_file: Cleaned_Real_Combined_data.csv
  
  split_data: 
    split_data_dir: split_data_dir
    train_data_dir: train_data_dir
    test_data_dir: test_data_dir
    train_data_file: train_data.csv
    test_data_file: test_data.csv
  
  model: 
    model_dir: trained_model
    decision_tree_reg: decision_tree_regression.pk1
    lasso_reg: la sso_regression.pk1
    ridge_reg: ridge_regression.pk1
    linear_reg: linear_regression.pk1
    random_forest_reg: random_forest_regression.pk1
    xgboost_reg: xgboost_regression.pk1
    finalized_model: finalized_model_ml.sav
    logistic_reg_model: logistic_reg_model.sav
    Alzheimer_model_latest : Alzheimer_model_latest.h5
    logistic_reg_RFE_model : logistic_reg_RFE_model.pk1
  
  reports: 
    reports_dir: reports_dir
    scores: scores.json                   # file name containing scores for the model training
    testing_scores: testing_scores.json   # the file name fo rthe scores of the loaded model on test data
    
    graphs:
      graphs_dir: graphs_dir
      trained_model_graph_dir: trained_model_graph_dir 

web_app:
  upload_folder: uploads  #here we will upload a the image for DL model prediction